[project]
name = "mujoco_template"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.30.1",
    "mediapy>=1.2.4",
    "mujoco>=3.3.5",
    "tqdm>=4.67.1",
]
